# permissions to do viewer templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-viewer-role
rules:
- apiGroups:
  - esc.k06.in
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - esc.k06.in
  resources:
  - templates/status
  verbs:
  - get
