# permissions to do viewer userlands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userland-viewer-role
rules:
- apiGroups:
  - esc.k06.in
  resources:
  - userlands
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - esc.k06.in
  resources:
  - userlands/status
  verbs:
  - get
