apiVersion: esc.k06.in/v1alpha2
kind: Template
metadata:
  name: vscode
spec:
  template:
    spec:
      containers:
      - image: codercom/code-server:3.8.0
        name: code-server
        args: ["--auth","none","project"]
  service:
    ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 8080
  volumes:
  - name: user-volume
    volumeMount:
      containerName: code-server
      mountPath: /home/coder/project
    pvcSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: longhorn
